```gaiacli stake create-validator --amount=1steak --pubkey=<your_node_pubkey> --address-validator=<your_account_address> --moniker=<your_name> --chain-id=gaia-6002 --sequence=0 --name=<your_key_name>```

Make sure the --pubkey used here is <your_node_pubkey> `gaiad tendermint show_validator` which is the node public key and --address-validator used is <your_account_address> `gaiacli keys list` which holds coins. If the transaction goes well, you have declared a validator candidate with 1 bonding steak on your validator node.

### cosmosaccaddr

   * Derived from account keys generated by gaiacli keys add
   * Used to receive funds
   * e.g. cosmosaccaddr15h6vd5f0wqps26zjlwrc6chah08ryu4hzzdwhc

### cosmosaccpub

    * Derived from account keys generated by gaiacli keys add
    * e.g. cosmosaccpub1zcjduc3q7fu03jnlu2xpl75s2nkt7krm6grh4cc5aqth73v0zwmea25wj2hsqhlqzm

### cosmosvalpub

    * Generated when the node is created with gaiad init.
    * Get this value with gaiad tendermint show_validator
    * e.g. cosmosvalpub1zcjduc3qcyj09qc03elte23zwshdx92jm6ce88fgc90rtqhjx8v0608qh5ssp0w94c

cosmosaccaddr15wkl5rq6uk8qdnpehdkp7clng255e06z2p9lfk
cosmosvalpub1zcjduepqy3v8k3lmu9q5l5jm3h8r69c9knef6zr6xzyc4jzgp9l90eh0m40stjefm3
